const DX = 8;
const DY = 8;
const NET_WIDTH = 48;
const NET_HEIGHT = 64;
const CMP_WIDTH = 200;
const CMP_HEIGHT = 32;
const CMP_HEIGHT2 = 16;
const TXT_HEIGHT = 16;
const XOFFSET = DX + CMP_WIDTH;
const YOFFSET = DY + NET_HEIGHT;
const XSLOT = DX + NET_WIDTH;
const YSLOT = DY + CMP_HEIGHT;
const PXOFFSET = 320;
const PYOFFSET = 56;

export default {
  DX: DX,
  DY: DY,
  NET_WIDTH: NET_WIDTH,
  NET_HEIGHT: NET_HEIGHT,
  CMP_WIDTH: CMP_WIDTH,
  CMP_HEIGHT: CMP_HEIGHT,
  CMP_HEIGHT2: CMP_HEIGHT2,
  TXT_HEIGHT: TXT_HEIGHT,
  XOFFSET: XOFFSET,
  YOFFSET: YOFFSET,
  XSLOT: XSLOT,
  YSLOT: YSLOT,
  PXOFFSET: PXOFFSET,
  PYOFFSET: PYOFFSET
};
